### ISSUE TITLE
Custom import paths not working

### ISSUE THREAD

**Issue by thijsvandercaaij** [probablykory/location-tools#2]
Hi Kory,

First of all, thanks for converting Balrond's tools into this easy to use package.

However, as the title says, custom import paths don't seem to work. As a workaround I put all my vanilla Valheim prefabs into Assets/PrefabInstance, but this is not ideal.

I had a look at FindPrefab but I'm not sure what's going wrong. If I don't put the prefabs in the default path I get the "Import was unable to find:" log for all prefabs in the blueprint.

Best Regards,
Thijs

**Comment by probablykory** [comment]
Yeah I've been meaning to update how that works.  You have to make sure there's a trailing / after the path. 
![image](https://github.com/probablykory/location-tools/assets/43595157/9c824849-2a62-4d10-8985-a116ee07cce2)

What version of Unity editor are you using?

Also are there any exception stacktraces in the log?

**Comment by thijsvandercaaij** [comment]
Oh dear did I really just forgot to trail it with a forwardslash... It's working now yeah... Thanks! After the importing the combine button under simple mesh combine stays greyed out however. I am able to combine using the old method. What's the difference?

Unity 2022.3.17f1 by the way.

**Comment by probablykory** [comment]
Valheim ships with a component called SimpleMeshCombine, which pretty much does the same thing as the older tool, but it has a couple more features and in general its behavior is more predictable.
![image](https://github.com/probablykory/location-tools/assets/43595157/35ee1399-f452-4134-bcde-b2307a758a1c)
The tool I added will search for that component on any children of the current selection, and when you directly select it, the tool will enable allowing you to invoke the combine logic.
